spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/danyhry/microservices.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
  port: 8071